name: Bridge tests

on:
  push:
    branches: [ master, main, dev ]
  pull_request:
    branches: [ master, main, dev ]

jobs:
  gravity:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test:
          - name: HAPPY_PATH
          - name: VALIDATOR_OUT
          - name: VALSET_STRESS
          - name: BATCH_STRESS
          - name: V2_HAPPY_PATH
          # TODO migrate the test to goerli
          # - name: RELAY_MARKET
          #  secret_arg: ALCHEMY_KEY
          - name: ORCHESTRATOR_KEYS
          - name: VALSET_REWARDS
          - name: EVIDENCE
          - name: TXCANCEL
          - name: INVALID_EVENTS
          - name: UNHALT_BRIDGE
          - name: PAUSE_BRIDGE
          - name: DEPOSIT_OVERFLOW
          - name: ETHEREUM_BLACKLIST
          - name: AIRDROP_PROPOSAL
          - name: SIGNATURE_SLASHING
          - name: SLASHING_DELEGATION
          - name: IBC_METADATA
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          cd tests/gravity
          /bin/bash all-up-test.sh ${{ matrix.test.name }} ${{ secrets[matrix.test.secret_arg] }}